### ISSUE TITLE
Google oauth error

### ISSUE THREAD

**Issue by ericmak624** [cool2build/no-line#14]
When using Google to sign in, after begin redirecting from /auth/google/callback, the user will receive the following error: 
`
Error
at /Users/{user}/Documents/projects/no-line/node_modules/passport-google-oauth20/lib/strategy.js:95:21
at passBackControl (/Users/{user}/Documents/projects/no-line/node_modules/oauth/lib/oauth2.js:132:9)
at IncomingMessage.<anonymous> (/Users/{user}/Documents/projects/no-line/node_modules/oauth/lib/oauth2.js:157:7)
at emitNone (events.js:110:20)
at IncomingMessage.emit (events.js:207:7)
at endReadableNT (_stream_readable.js:1059:12)
at _combinedTickCallback (internal/process/next_tick.js:138:11)
at process._tickCallback (internal/process/next_tick.js:180:9)
`

**Comment by ericmak624** [comment]
fixed in PR #16
